### ISSUE TITLE
How to enable filtering without the toolbar

### ISSUE THREAD

**Issue by mikepc** [adazzle/react-data-grid#794] opened 2017-05-16 19:16 UTC
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[] v0.14.x
```

```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ X] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[X] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Digging through the source code it's not clear to me how I can enable filtering on the grid without using the toolbar.

**Expected/desired behavior**

The primary problem is that I don't know how to mutate the state of the grid to enable canFilter to be true programmatically. I just want the filters to be enabled by default and not be able to disable them.

Alternatively, if I use AdvancedToolbar I don't know how to wire canFilter to a custom button so that I can render a button that has an icon on it. 

It would be awesome if there was a prop on the main grid that we could just manage the state from the consumer, without using the toolbar!

**Comment by mhcdionisio** [comment] 2017-05-19 03:03
Also looking for something like that!

**Comment by bplatta** [comment] 2017-05-31 17:07
I wanted this as well. Here's the hack I had to do:

```
class Toolbar extends Component {
  componentDidMount() {
    this.props.onToggleFilter();
  }

  render() {
    return null;
  }
}

// and then rendered in component:
<ReactDataGrid
          columns={this.Columns}
          rowsCount={numberRows}
          rowGetter={rowGetter}
          onGridSort={this.onGridSort}
          toolbar={<Toolbar />}
          onAddFilter={this.onAddFilter}
          minHeight={minHeight} />
```

**Comment by YanaSavchenko** [comment] 2017-07-14 16:23
I have another workaround till the issue is not fixed. I'm using React-data-grid + Material UI. No toolbar. No problem with horizontal scroll.

1. First, lets create custom header

Our column will look like
```
{
       key: 'Price',
       name: 'Price',
       width: 100,
       headerRenderer: this.headerRenderer(
            'Price',
            'Price'
      )
}
```

Our formatter
```
headerRenderer(className, label) {
        return (
            <TextField
                className         = {className}
                floatingLabelText = {label}
                type              = 'text'
                fullWidth         = {true}
                onValueUpdate     = {this.handleFilterChange.bind(null, className)} />
        );
    }
```

2. Now we need to create filter that has same structure as React-data-grid
```
handleFilterChange(key, value) {
        const newFilters = Object.assign({}, this.state.filters);

        if (value) {
            const filter = {
                filterTerm: value,
                column: _.find(this.getColumns(), ['key', key])
            }

            newFilters[key] = filter;
        } else {
            delete newFilters[key];
        }

        this.setState({ filters: newFilters });
    }
```

3. The table component looks like this
```
<ReactDataGrid
        minHeight    = {minHeight}
        onAddFilter  = {this.handleFilterChange}
        columns       = {this.getColumns()}
        rowGetter    = {this.rowGetter}
        rowsCount   = {this.getSize()} />
```

Result
![image](https://user-images.githubusercontent.com/10143921/28220613-c5854dea-6885-11e7-9d22-b6b9d41aa022.png)
![image](https://user-images.githubusercontent.com/10143921/28220596-b56b6246-6885-11e7-8c56-a5e0dc05bccf.png)

**Comment by wasabigeek** [comment] 2018-01-10 09:12
@YanaSavchenko how do you bind `this` for `this.state.filters` to work?

**Comment by jacek-jaskolski** [comment] 2018-02-08 17:25
Have a look at https://github.com/adazzle/react-data-grid/issues/919#issuecomment-364181119

**Comment by amanmahajan7** [comment] 2018-03-24 22:47
Duplicate issue, closing in favor of #669

**Closed by amanmahajan7** 2018-03-24 22:47 UTC

**Comment by sun2rise** [comment] 2018-07-07 09:05
Hi @YanaSavchenko ... do you have a https://codesandbox.io/ example of that? the solution kinda works but i cannot see the textfield properly. how did you remove the toolbar in your solution?
thanks
