### ISSUE TITLE
Checkbox for row is not locked when scrolling horizontally

### ISSUE THREAD

**Issue by computerlove** [adazzle/react-data-grid#546] opened 2016-11-30 15:23 UTC
**WHICH VERSION OF REACT ARE YOU USING?**
```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[x] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When using `rowSelection` with `showCheckbox: true` the checkbox in the header row is locked, but checkboxes on each row scroll with the other columns.
![scroll](https://cloud.githubusercontent.com/assets/769579/20758051/dae9be6a-b718-11e6-841f-63e5a3772e32.gif)

**Expected/desired behavior**
Checkbox in header and checkboxes in rows are both locked or both scroll.

**Reproduction of the problem**
* Edit http://adazzle.github.io/react-data-grid/examples.html#/row-select 
* Set width for all columns and add enough columns to make the scrollbar appear.

```
  getColumns: function() {
    return  [
      {
        key: 'id',
        width: 300,
        name: 'ID'
      },
      {
        key: 'title',
        width: 300,
        name: 'Title'
      },
      {
        key: 'count',
        width: 300,
        name: 'Count'
      },
      {
        key: 'count2',
        width: 200,
        name: 'Count2'
      },
      {
        key: 'count3',
        width: 200,
        name: 'Count3'
      },
      {
        key: 'count4',
        width: 200,
        name: 'Count4'
      },
      {
        key: 'count5',
        width: 200,
        name: 'Count5'
      }
      
    ];
  }
```

**Comment by jpdriver** [comment] 2016-11-30 17:20
seems to be affecting general examples as well -- see http://adazzle.github.io/react-data-grid/examples.html#/fixed-cols

**Comment by dkwin** [comment] 2016-12-05 12:30
It seems that all browsers I've tried with, the columns seem broken (Edge, Chrome, firefox).

**Comment by malonecj** [comment] 2016-12-12 11:19
Looks to be the same issue as this
https://github.com/adazzle/react-data-grid/issues/560

**Comment by malonecj** [comment] 2016-12-21 15:21
This is fixed now

**Closed by malonecj** 2016-12-21 15:21 UTC
Labels: Accepted, bug

**Comment by tonytangau** [comment] 2017-10-18 09:21
Still reproducible in version 2.0.60, under latest Chrome

**Comment by praveendabral** [comment] 2018-07-27 05:46
Still reproducible in version 4.0.7
