### ISSUE TITLE
grid-template-rows not updating after add a new row

### ISSUE THREAD

**Issue by vine1993** [adazzle/react-data-grid#2967] opened 2022-07-20 23:21 UTC
## Describe the bug
I'm using a simple array state to store my rows, I have a modal window that creates a new row to the grid, but when I do that the grid-template-rows under the grid don't update the repeat to the new length, this causes the UI to break.
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/2659288/180098574-32a4db7c-6b97-4a98-9bda-80d1b9c14928.png">
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/2659288/180098844-4008bb7d-d1ac-473f-acd7-1e0546c9de77.png">

## To Reproduce 

1. Create a simple state `const [data, setData] = useState([])`
2. Try to insert a new row to this state

## Environment

- `react-data-grid` version: 7.0.0-beta.12
- `react`/`react-dom` version: 16.14.0 / 16.11.0

**Comment by szatpig** [comment] 2022-09-15 04:13
met the same

**Comment by chirayuchiripal** [comment] 2022-09-23 16:30
Possible duplicate of: https://github.com/adazzle/react-data-grid/issues/2956

**Comment by amanmahajan7** [comment] 2022-09-23 19:33
Can you create a reproducible example? Also make sure you are not mutating rows and creating a new array instead.

**Comment by PopeyeSailorMike** [comment] 2022-09-25 20:33
Any solution to this. I'm trying to implement the Master-detail Grid and I would love to be able to add or delete rows at the Master Level.

**Comment by amanmahajan7** [comment] 2022-12-23 16:15
Closing this issue for now as there is no reproducible example. Feel free to create a new issue if you are still facing the problem.

**Closed by amanmahajan7** 2022-12-23 16:15 UTC
Labels: Bug
