### ISSUE TITLE
Resize handle is invisible in Safari.

### ISSUE THREAD

**Issue by solar-vibez** [adazzle/react-data-grid#2807] opened 2022-02-02 09:54 UTC
## Describe the bug 
Reproduced, for example at https://adazzle.github.io/react-data-grid/#/all-features in Safari.
There is no "col-resize" cursor appearing when mouse is close to the right border.  The feature is working, but it's quite challenging to point the cursor in the right place.

It's working perfectly in Chrome or Firefox on the same Mac installation.

## Expected behavior 
Cursor should be changed to "col-resize" when resizable feature is enabled in all supported browsers.
## Environment

- `react-data-grid` version: 7.0.0-beta.7
- `react`/`react-dom` version: 16.14.0
- Mac OS 12.0.1 Monterey
- Safari Version 15.1 (17612.2.9.1.20)

**Comment by amanmahajan7** [comment] 2022-03-25 02:20
Is this still an issue in the latest safari?

**Comment by solar-vibez** [comment] 2022-03-25 08:15
Just checked in Safari Version 15.4 (17613.1.17.1.6). Issue is still here.

**Comment by devnaumov** [comment] 2022-06-15 11:14
Seems like the problem is .rdg-cell-resizable::after pseudo-element. The cursor: col-resize works fine in safari if it is applied to the div.

**Comment by nstokoe** [comment] 2022-08-29 17:50
Still happening on safari Version 15.6 (17613.3.9.1.5) with v7-beta-12

**Comment by amanmahajan7** [comment] 2023-09-19 19:57
This should be fixed in the latest version as resize handle is a real DOM element now

**Closed by amanmahajan7** 2023-09-19 19:57 UTC
Labels: Bug
