### ISSUE TITLE
Is multi cell selection supported in 7.0.0-canary.26?

### ISSUE THREAD

**Issue by omfgitsjack** [adazzle/react-data-grid#2183] opened 2020-10-21 16:01 UTC
With the removal of cellRangeSelection, is there a way to select a range of cells?

**Comment by amilich** [comment] 2020-12-07 19:16
+1

**Comment by lucassarcanjo** [comment] 2021-03-22 17:35
Any updates?

**Comment by NoobTW** [comment] 2021-04-21 14:23
+1 for multi cell selection.

**Comment by nstepien** [comment] 2021-08-17 17:40
Closing as duplicate of #2260

**Closed by nstepien** 2021-08-17 17:40 UTC
