### ISSUE TITLE
Getting getDefaultProps warnings with react 15.6+

### ISSUE THREAD

**Issue by tjhubert** [adazzle/react-data-grid#978] opened 2017-10-19 14:59 UTC
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
current behavior:
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```
![image](https://user-images.githubusercontent.com/6811291/31777551-ea34ee6e-b4b3-11e7-9c56-80d580061f71.png)

desired behavior: no warnings

motivation: less noise in console warnings and compatibility to upgrade React

**Comment by aschonfeld** [comment] 2017-10-24 20:21
Looks like the following files still have references to getDefaultProps:

packages/react-data-grid-addons/src/editors/DateRangeEditor.js
packages/react-data-grid/src/ColumnMetricsMixin.js
packages/react-data-grid/src/Grid.js
packages/react-data-grid/src/Row.js
packages/react-data-grid/src/ViewportScrollMixin.js
packages/react-data-grid/src/Canvas.js
packages/react-data-grid/src/ReactDataGrid.js

But now that I look at the source code you're using createReactClass which means in order to fully convert this to the correct way of defining defaultProps you would have to change how you declare classes as well.  Not a tough thing to do, but also not a trivial task.

**Comment by kamaldlk** [comment] 2017-10-26 02:00
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead,

I'm getting same error please me on this

**Comment by jessie20000503** [comment] 2017-10-26 06:00
I also get the same error.

I use the basic example, and in my code :
import Example from './Example'
 <Example></Example>
the grid would display, but i would see lots of "Warning: getDefaultProps..." warings in log

i use the 15.4.2 react ,react-dom, and really don't know how to solve it, could anyone help me? Thanks a lot!

**Comment by jessie20000503** [comment] 2017-10-26 06:20
I saw aschonfeld's comment, do that mean react-data-grid need an upgrade to remove these es5 code to es6? Or is there something wrong with the code we use it?

**Comment by aschonfeld** [comment] 2017-10-26 11:35
Either they need to update hiw they declare getDefaultProps or you’ll need to downgrade the version of React you use in order to make these dissapear.

**Comment by wKovacs64** [comment] 2017-10-26 20:19
#970 was merged without updating these. Using `createReactClass` is the new/current way of defining class components in ES5 (no need to update to ES2015/ES6 if they don't want to) but `getDefaultProps` needs updated along with it. Looks like the codemod hit some of them, but the remaining occurrences may need manual intervention.

**Comment by jessie20000503** [comment] 2017-10-27 06:45
Thanks @aschonfeld @wKovacs64 ! I feel so strange , the example code has been in ES6 format ,  it seems that i have to give up using this component.

**Comment by utrolig** [comment] 2017-10-27 08:05
Any timeframe on when this will be fixed? I'm using version 2.0.66 and this isn't working with React 16.

**Comment by alienintheheights** [comment] 2017-10-28 16:49
Doesn't look like this code is being supported any longer. Last release 10 months ago and breaking with current React. Need to find another solution.

**Comment by wKovacs64** [comment] 2017-10-28 17:22
@jessie20000503 @alienintheheights I'll admit, the way this project is managed is mildly infuriating compared to most OSS, but it is definitely still being worked on. Ignore the releases tab on GitHub - that's based on git tags and apparently they haven't tagged anything since 2.0.2, but 2.0.69 was released just [yesterday](https://github.com/adazzle/react-data-grid/commit/d28033690ed82161fd420ff2d7c5fae282378355) (2017-10-27).

If you want to use React 16 before this project officially supports it (without the warning spam introduced in 2.0.61 due to #970), use version 2.0.60 with the [little hack I mentioned](https://github.com/adazzle/react-data-grid/issues/744#issuecomment-333890937) in #744. There are a couple follow-up comments below it for `create-react-app` and TypeScript as well.

**Comment by alienintheheights** [comment] 2017-10-28 17:24
Good to know it's still active because I haven't found anything better. I'm not on React 16 though. Getting these errors with 15.6.1.

**Comment by wKovacs64** [comment] 2017-10-28 17:34
In that case, you can still use 2.0.60 but skip the hack. You'll get a couple deprecation warnings, but not the slew of warnings shown above.

**Comment by amanmahajan7** [comment] 2017-10-30 23:45
Defining `getDefaultProps()` as a `function` is the correct way of using it with `createReactClass`
https://reactjs.org/docs/react-without-es6.html#declaring-default-props

The problem seems to occur when development and production versions of `react` and `create-react-class` are mixed. 

> To fix the false positive warnings, you need to either use:
> - react.js and create-react-class.js (development)
> - react.min.js and create-react-class.min.js (production)


https://github.com/facebook/react/issues/9999#issuecomment-310035475

**Comment by amanmahajan7** [comment] 2017-10-30 23:47
It is probably a good idea to revisit `react-data-grid` bundling and decide whether `create-react-class` should be included in the bundle or specified as a peer dependency

**Comment by wKovacs64** [comment] 2017-10-30 23:52
Interesting. Good catch, @amanmahajan7!

**Comment by kamaldlk** [comment] 2017-10-31 02:22
![screen shot 2017-10-31 at 7 47 07 am](https://user-images.githubusercontent.com/9652523/32204626-710d9ea8-be10-11e7-8784-484e3f1d3c9d.png)

**Comment by kamaldlk** [comment] 2017-10-31 02:24
please check below url 

https://codesandbox.io/s/3z3lq9zn1

Thanks 
Kamal

**Comment by pidupuis** [comment] 2017-10-31 16:32
Same problem here, need fix

**Comment by activebiz** [comment] 2017-11-01 13:14
I am getting same issue here. It will need to be fixed. Do we know any timeline?

**Comment by josh08h** [comment] 2017-11-02 12:30
Same warnings with React Fiber.

Although you say React Fiber is "Not officially supported, expect warnings and errors" so it is expected I guess.

**Comment by philquinn** [comment] 2017-11-02 23:54
#1006 can I get some eyes on this? Hopefully this resolves some of these warnings. (hopefully them all)

**Comment by dklanac** [comment] 2017-11-03 22:06
I confirm that setting the package version to `2.0.60` exactly (no `^` mark) eliminates this problem on React `15.6.2`.

Thanks for such an awesome project. This is still the most flexible data grid that I've come across.

**Comment by kamaldlk** [comment] 2017-11-06 12:30
Hi all any update on this :( , im planning to use my product  pls help me to fix this

**Comment by kamaldlk** [comment] 2017-11-08 02:04
this 2 files didn't add - ( create-react-class) pls check @amanmahajan7  
ColumnMetricsMixin.js
ViewportScrollMixin.js

**Comment by dijonkitchen** [comment] 2017-11-14 21:37
@dklanac Where do you see `2.0.60`? The latest release or tag is [`2.0.2`](https://github.com/adazzle/react-data-grid/releases)

**Comment by gymneganesh** [comment] 2017-11-15 23:36
Getting the same error as well and I am using 
   "react-data-grid": "^2.0.73",
    "react-data-grid-addons": "^2.0.73",

**Comment by dklanac** [comment] 2017-11-16 01:30
@dijonkitchen I just followed what @ wKovacs64 mentioned in his earlier post. I didn't check the version history in this project, but it works. I don't see any glaring issues with 2.0.60 vs. 2.0.73 at the moment.

**Comment by elderapo** [comment] 2017-11-16 02:53
Temp workaround:
```
export const disableGetDefaultPropsWarning = () => {
    const warning = "Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.";
    const consoleError = console.error.bind(console);

    console.error = (...args) => {
        if (args[0] === warning) return;
        return consoleError(...args);
    };
};
```
Just call this function before importing "react-data-grid".

**Comment by amanmahajan7** [comment] 2017-11-17 17:57
#1012 does not work as expected, reverted changes and reopening this issue

**Comment by jpdriver** [comment] 2017-11-20 08:00
IMO I think we should revert #954 (move to `prop-types`) and #970 (move to `create-react-class`). The reality is that we were not -- and are not -- ready to adopt ES6 syntax or modern React architecture.

This will be the case as long as we're still using Mixins; which were considered as a powerful pattern circa React 11 (when this lib dates from) but are now strongly discouraged.

They are the ultimate root cause of the PropTypes validation errors introduced with #954 and the warnings about using defaultProps in a Mixin-based architecture in #970.

As far as support for React 15.5+ / 16 goes, I suggest we ship the import shim @wKovacs64 mentioned here https://github.com/adazzle/react-data-grid/issues/744#issuecomment-333890937. This will address all the warnings in a stable and production-friendly manner, whilst also enabling the Grid to be used immediately with React 16.

Officially shipping that would allow us time to clean up the architecture internally without it affecting either external users or Adazzle internally.

@amanmahajan7 @malonecj

**Comment by BenLDouthwaite** [comment] 2017-11-20 12:04
@amanmahajan7 Could you confirm why #1012 did not work as intended? it appeared to work correctly on one of my projects

**Comment by amanmahajan7** [comment] 2017-11-20 14:47
@BenLDouthwaite #1012 broke the example site, it also works as intended on the local environment. I will revisit this PR

**Comment by amanmahajan7** [comment] 2017-11-20 16:30
@jpdriver @malonecj I think instead of reverting #954 (move to `prop-types`) and #970 (move to `create-react-class`), it would be better to replace `createReactClass` with `React.createClass`. This will generate a handful of `development` time deprecation warnings. `React.createClass` warnings are logged when `createClass` [method is called](https://github.com/facebook/react/blob/v15.6.2/src/isomorphic/React.js#L124) unlike `defaultProps` warnings which are logged every time an element is [created on cloned](https://github.com/facebook/react/blob/v15.6.2/src/isomorphic/classic/element/ReactElementValidator.js#L262). Also, there are a few components that can be manually converted to class components without too much work.

**Comment by arkanmgerges** [comment] 2017-12-02 08:47
Hi,
I have the same problem, I'm using "react": "15.6.2", I'm receiving "Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead."

I look at the code, and it needs to be refactored, also my opinion to get rid of mixins and use other solutions like utility objects, component compositions, high-order components ...etc, these are found by the article written by Dan Abramov, from the official react js website blog [Mixins Considered Harmful](https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html), written by Dan Abramov,
He is working on reactjs. Co-author of Redux and Create React App.

The way to write reactjs class in ES6 does not support mixins, and defaultProps is defined as a property not as a function, but with createReactClass() is defined as a function, [Declaring Default Props](https://reactjs.org/docs/react-without-es6.html#declaring-default-props)

Thanks

**Comment by kaiyoma** [comment] 2017-12-04 10:18
This is my highest priority issue with react-data-grid, so I would also like to see this fixed soon. When I interact with the table, I get literally thousands of errors in the console, which makes debugging other issues unnecessarily difficult.

**Comment by PredokMiF** [comment] 2017-12-04 11:05
I hope, that out communiti will fix it soon, but now you can set filter in Chrome devtool console, like this:
```/^((?!getDefaultProps)[\s\S])*$/```

**Comment by barbalex** [comment] 2017-12-11 21:22
this issue prevented me from using this library

**Comment by mdarif** [comment] 2017-12-13 08:08
+1, we also have been facing the same issue.

**Comment by utajum** [comment] 2017-12-13 08:49
+1 same problem here

**Comment by 29er** [comment] 2017-12-14 21:59
we decided not to use this grid as we are on React16 , and too many issues. bah humbug

**Comment by kaiyoma** [comment] 2017-12-15 03:19
Same here. Too many issues and not enough documentation.

**Comment by kaiyoma** [comment] 2017-12-15 06:43
I switched to [react-virtualized](https://github.com/bvaughn/react-virtualized) and it's been working out really well so far.

**Comment by 29er** [comment] 2017-12-18 17:56
we are now using https://github.com/agracio/ts-react-json-table . it's been doing the job fine for our needs.

**Comment by stevewillard** [comment] 2017-12-18 18:02
If you're looking for a canvas based solution, and need a high performant data grid which can handle thousands of rows and columns, I highly recommend https://github.com/TonyGermaneri/canvas-datagrid

There are very few canvas solutions out there, and I found this one to be great. The documentation is quite good, too.

**Comment by mgcdanny** [comment] 2018-01-02 22:31
After hitting this issue, I searched around and am trying this: https://devexpress.github.io/devextreme-reactive/react/grid/

**Comment by DamienNsh** [comment] 2018-01-04 08:22
Any information about the fix ?

All your projects are good but they don't help me.
I search a grid where it is possible to edit one cell and disable the editing on a column.
It must also have filters for the column and it can.

PS: are you coding a version that works with react 16?

(happy new year)

**Closed** 2018-01-10 09:46 UTC

**Comment by mmabraham** [comment] 2018-01-10 21:04
I used this hack to suppress the error in test files:
```
const _error = window.console.error;
const warningToSuppress = 'Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.';
export const suppressError = () => {
    window.console.error = (errorText) => {
        if (errorText && errorText.indexOf(warningToSuppress) >= 0) {
            return null;
        } else {
            _error(errorText);
        }
    }
}
```
Still hoping that this issue will be fixed though as it is blocking us from upgrading to React 16.

**Comment by amanmahajan7** [comment] 2018-01-10 21:18
@mmabraham, this issue has been fixed. Please upgrade to v3
https://github.com/adazzle/react-data-grid/blob/master/migrations/v2-v3.md

**Comment by yoDon** [comment] 2018-03-10 22:35
@mmabraham I believe v3 only fixes the React 15.5+ incompatibility for react-data-grid, not for react-data-grid-addons. 

react-data-grid v3.0.11 is working fine with React 15.6 but anything I try to pull in from react-data-grid-addons throws the PropTypes and createClass exceptions. @wKovacs64's [3-4 line hack](https://github.com/adazzle/react-data-grid/issues/744#issuecomment-333890937) seems to still be required to get the v3.0.11 react-data-grid-addons to work.

**Comment by amanmahajan7** [comment] 2018-03-11 22:06
@yoDon `v3` does not officially support `React 15.5.x` and `React 16.x` and it is possible that some of the  dependencies of `react-data-grid-addons` are still using `React.createClass` and `React.PropTypes`. Apart from the deprecation warnings, `v3` should work with `React 15.x.x`.

We are actively working on [`v4`](https://github.com/adazzle/react-data-grid/tree/next) that will remove all the deprecation warnings and will be fully compatible with `React 15` and `React 16`.

**Comment by oliverwatkins** [comment] 2018-03-30 14:31
I'm also going to have to dump this component. Such a trivial warning... how hard can it be to fix?

**Comment by vdsheryarshirazi** [comment] 2018-11-25 14:03
Is there anyway to get this error in eslint/babel-eslint?
