### ISSUE TITLE
peerInvalid on npm install 

### ISSUE THREAD

**Issue by geocontrol** [adazzle/react-data-grid#459] opened 2016-09-20 21:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
INstalling via npm 

package.json has 

	"react": "*",
	"react-dom": "*",
	"react-data-grid": "*",

But getting peer invalid as react and react-dom are @15.3.2 and react-data-grid requires ~0.14.6

**Comment by rhmoller** [comment] 2016-09-23 07:26
Duplicate of #280

**Comment by diogofcunha** [comment] 2016-09-26 09:11
Hi @geocontrol.

Not supporting react 15 at this moment.

As @rhmoller said lets keep this discussion in #280.

Cheers.

**Closed by diogofcunha** 2016-09-26 09:11 UTC
