### ISSUE TITLE
How to force update grid columns

### ISSUE THREAD

**Issue by happyheartman** [adazzle/react-data-grid#709] opened 2017-03-22 09:10 UTC
Hi,

I have the grid with two columns "Column A" & "Column B".
I setstate and change the columns to "Column B" & "Column A".

But the grid didn't refresh and the columns are still "Column A" & Column B"

**Comment by martinnov92** [comment] 2017-03-22 13:59
@happyheartman Hi, same is happening to me, I have to do `this.setState({ columns: []})` and then  `this.setState({ columns: [ column A, column B ,....]}) `, not the best solution I know, but it helped me...

**Comment by happyheartman** [comment] 2017-03-23 06:09
@martinnov92 What I did is add extra " " character to the name of one column and the grid columns will updates. So i;m alternating " " & "" when setState(columns) . Seems like the grid is checking object changes to update the grid for performance.

**Comment by phkavitha** [comment] 2017-03-23 17:09
I too had a similar situation. I had to update the width of the columns so that the column gets expanded when the rows are rendered. I used slice() to create a new reference to the columns variables and then changed the state. Something like
```
let updatedColumns = myOldColumns.slice();
// modified updatedColumns
this.setState({
     columns: updatedColumns
})
```
Hope it helps

**Comment by Whythawye** [comment] 2017-04-06 22:39
I was having a similar situation with updating grid data en masse, and found this helpful: https://github.com/adazzle/react-data-grid/issues/332

**Comment by Poetro** [comment] 2017-09-19 09:37
The issue is, that the detection of the column change is broken. It only checks if the columns in the previous column list do exist in the new list, which is true, but it does not check, if they are in the same order, so it does not re-render. Also going forward to React 16+, the double `setState` wont even work, as they will be merged into one `setState`.

The `compareEachColumn` [function](https://github.com/adazzle/react-data-grid/blob/5088a9da098c1005a029642cb32d7b33e72b12d4/packages/react-data-grid/src/ColumnMetrics.js#L116) needs to be fixed to check for the order as well, not just existence, which IMO would result in a shorter and cleaner code as well.

**Comment by pgn-vole** [comment] 2017-10-19 15:02
I just opened an PR to fix this issue.

**Comment by mervick** [comment] 2018-04-25 05:25
Found a workaround, see my comment here https://github.com/adazzle/react-data-grid/issues/197#issuecomment-384084671

**Closed** 2018-07-19 11:39 UTC
Labels: wontfix

**Comment by aditya777hp** [comment] 2018-07-27 11:16
grid.setColumnTitle(index.'nameIwant'); is also not working guys !!!

**Comment by nasmithan** [comment] 2018-08-15 06:28
None of the suggestions above are working. I'm trying to add a column based on user input, so they can add/remove columns to display on the fly. The rows data underneath already has all columns present, I just don't have the room to display all 20 columns.

**Comment by aditya777hp** [comment] 2018-08-23 06:57
https://fancygrid.com/api/methods/hidecolumn
have you  tried this  ??
If not set a Boolean variable to the hidden attribute and try by reloading the grid after the user input has been taken !!!
Which framework are you working with ??
Lemme know more

**Comment by patwalls** [comment] 2019-12-06 02:01
Thank you @neotan you are a god send!!

**Comment by neotan** [comment] 2019-12-06 02:06
@patwalls u r welcome =)

**Comment by emsi-iggy** [comment] 2020-04-20 00:17
@neotan 
Actually you don't need to change all the columns.
Only one column need to be changed, and it can change from false to true and vice versa.

Let's assume we have in state columns:
```
columns: [
      {
        key: "id",
        name: "ID",
        width: 50,
        draggable: true,
        unusedProperty: false, // <--- add some property and set to false
      },
      {
        key: "title",
        name: "Title",
        draggable: true,
        resizable: true,
      },
      {
        key: "count",
        name: "Count",
        draggable: true,
        resizable: true,
      }
    ],
```
```
onHeaderDrop = (source, target) => {
    let columns = [...this.state.columns];
    const columnSourceIndex = columns.findIndex(i => i.key === source);
    const columnTargetIndex = columns.findIndex(i => i.key === target);
    const temp = { ...columns[columnSourceIndex] };
    columns[columnSourceIndex] = { ...columns[columnTargetIndex] };
    columns[columnTargetIndex] = temp;

    //NEW code
    //lets change only column with key "id"
    const IndexOfIdColumn = columns.findIndex(i => i.key === "id");
    let IdColumn = { ...columns[IndexOfIdColumn] };
    IdColumn.unusedProperty = !IdColumn.unusedProperty; //<--change from true to false and vice versa
    columns[IndexOfIdColumn] = IdColumn;
    //END of new code
    this.setState({ columns });
  };
```
This code also works.
