### ISSUE TITLE
Use of separate PropTypes package to resolve warnings on React.CreateClass with react 15.5.4

### ISSUE THREAD

**Issue by hitheshbhat** [adazzle/react-data-grid#828] opened 2017-06-10 17:13 UTC
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome
```

```
Should work:
[X] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
Warning is shown about the use of PropTypes and React.CreateClass when used with React 15.5.4

**Expected/desired behavior**
PropTypes should be used which is provided as a separate package. Pure JavaScript class need to be used instead of CreateClass

**Reproduction of the problem**
React version upgrade to 15.5.4 shows the warnings instantly

**What is the expected behavior?**
Use of JavaScript classes and avoiding the use of PropTypes from React

**What is the motivation / use case for changing the behavior?**
The use of CreateClass and PropTypes will be deprecated in the next major version 16 release of React 

![image](https://user-images.githubusercontent.com/18732373/27004812-e01aecae-4e2d-11e7-806d-af1305f491d9.png)

**Comment by ryancogswell** [comment] 2017-06-12 14:39
This is a duplicate of issue #744

**Comment by amanmahajan7** [comment] 2017-08-16 03:33
Closing in favor of https://github.com/adazzle/react-data-grid/issues/744

**Closed** 2018-03-14 19:24 UTC
