### ISSUE TITLE
Cell editing issues when cell range selection is enabled

### ISSUE THREAD

**Issue by cleaver86** [adazzle/react-data-grid#1460] opened 2019-02-07 02:43 UTC
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome
---

### I'm submitting a ...

- [x] 🐛 Bug Report

---

### Issue Details

- What the current behavior is
When using cellRangeSelection in combination with editable columns there is some weird behavior when editing a cell. Currently when you enter a value in a cell editor, and then click on another cell, the value is entered into the newly selected cell rather than the original. See the following video: https://bit.ly/2Scqpi9

- What the desired behavior is
When the editor is open for a specific cell the value entered should be set on that cell.

- (If Bug) Steps to reproduce the issue
The issue can be recreated here: https://codesandbox.io/s/nrvr29x0lj

**Comment by cleaver86** [comment] 2019-02-07 18:57
So the reason this is happening is that when cellRangeSelection is used the grid binds to the mouseDown event rather than the click event to set the cell selection. This means the editor blur event is called after the cell selection has already updated and the wrong cell is now the target for the new value.

I'm current using a custom editor like this to get around the issue:
`class CustomEditor extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            value: this.props.value
        };
    }
    // The following workaround is necessary to prevent React Data Grid from
    // setting input data to the wrong cell when cellRangeSelection is used.
    componentDidMount() {
        document.addEventListener('mousedown', this.handleMouseDown, true);
    }
    componentWillUnmount() {
        document.removeEventListener('mousedown', this.handleMouseDown, true);
    }
    handleMouseDown = (e) => {
        e.stopPropagation();
        this.props.onCommit();
    }
    //////////////////////////////////////////////////////////////////////////
    getValue() {
        const key = this.props.column.key;
        return { [key]: this.state.value };
    }
    handleChange = (e) => {
        this.setState({ value: e.target.value });
    };
    getInputNode() {
        return this.refs.input;
    }
    disableContainerStyles() {
        return true;
    }
    render() {
        return (<input
            ref="input"
            value={this.state.value}
            onChange={this.handleChange}
            style={{
                width: this.props.column.width,
                height: this.props.height
            }}
        />);
    }
}`

**Comment by jimitit** [comment] 2019-02-14 12:33
Same issue coming to me..

**Comment by szogun1987** [comment] 2019-03-20 15:54
It is fixed in this PR: https://github.com/adazzle/react-data-grid/pull/1489

**Closed** 2019-04-26 17:19 UTC
Labels: bug, wontfix

**Comment by zahidraza** [comment] 2019-05-14 20:04
This is a very critical bug for using copy and paste feature. 

The issue is still not fixed but has been automatically closed.
