### ISSUE TITLE
Drodown crashes browser tab when start editing by press "enter" key

### ISSUE THREAD

**Issue by KamilPuczka** [adazzle/react-data-grid#1639] opened 2019-05-07 11:23 UTC
---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x ] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ x] 🐛 Bug Report
- [ ] 💡 Feature Request

### Issue Details
Hi,

when try to enable dropdown edition pressing "enter" key, whole tab/editor crashes. To reproduce:
-select cell with dropdown editor
-press enter

**Comment by vitorhorta** [comment] 2019-05-27 14:56
Any news on this issue? Still having the same problem on 6.1.0.

**Comment by benlongmire** [comment] 2019-06-18 00:00
Have experienced the same issue on Windows, however using a Mac I'm unable to reproduce the issue.

**Comment by cbattleNTT** [comment] 2019-07-16 10:55
I'm having the same issue, also with version 6.1.0, on a Windows 10 64-bit machine using Chrome 75. It didn't happen on Chrome 72 and it doesn't happen for me in Firefox or IE

**Comment by cbattleNTT** [comment] 2019-07-16 11:48
I also see that this issue happens with the  [RDG Editor example] (https://codesandbox.io/s/vq5387plyy?from-embed) in the docs and above. The exact Chrome version that this happens in is: Version 75.0.3770.100 (Official Build) (64-bit)

I couldn't reproduce the issue in previous Chrome versions

**Comment by cbattleNTT** [comment] 2019-08-01 12:26
Any news on this issue? It also happens in the new Chrome version that just came out:
Version 76.0.3809.87 (Official Build) (64-bit)

**Comment by benlongmire** [comment] 2019-08-01 13:21
I believe one of my Devs worked this out. I'll let you know ASAP

**Comment by cbattleNTT** [comment] 2019-09-27 15:44
@benlongmire Did you manage to make progress on this issue? We're still having it with our drop-down so I wanted to check back in.

**Comment by benlongmire** [comment] 2019-09-28 00:33
I believe we solved the problem by creating our own dropdown as we needed
something custom. Perhaps it was to do with the on blur method. I can't
really remember beyond that though unfortunately.

**Comment by cbattleNTT** [comment] 2019-09-30 07:00
Okay thanks, I'll look into it

**Comment by amanmahajan7** [comment] 2021-05-21 17:51
Looks like this issue does not exists in canary so I am closing this 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Closed by amanmahajan7** 2021-05-21 17:51 UTC
