### ISSUE TITLE
`onColumnsReorder` not triggering on NextJS

### ISSUE THREAD

**Issue by softmarshmallow** [adazzle/react-data-grid#3585] opened 2024-08-25 09:41 UTC
- NEXTJS https://codesandbox.io/p/devbox/react-data-grid-colum-reorder-not-working-nextjs-xkxp6x
- CRA https://codesandbox.io/p/sandbox/react-data-grid-colum-reorder-not-working-yqlkm2

With exact same code, the reordering won't trigger on nextjs.

(from website demo) - https://github.com/adazzle/react-data-grid/blob/main/website/demos/ColumnsReordering.tsx
```tsx
"use client";
import "react-data-grid/lib/styles.css";

import { useCallback, useMemo, useState } from "react";

import DataGrid, { Column, SortColumn } from "react-data-grid";
// import type { Props } from "./types";

interface Row {
  readonly id: number;
  readonly task: string;
  readonly complete: number;
  readonly priority: string;
  readonly issueType: string;
}

function createRows(): Row[] {
  const rows: Row[] = [];

  for (let i = 1; i < 500; i++) {
    rows.push({
      id: i,
      task: `Task ${i}`,
      complete: Math.min(100, Math.round(Math.random() * 110)),
      priority: ["Critical", "High", "Medium", "Low"][
        Math.round(Math.random() * 3)
      ],
      issueType: ["Bug", "Improvement", "Epic", "Story"][
        Math.round(Math.random() * 3)
      ],
    });
  }

  return rows;
}

const columns: Column<Row>[] = [
  {
    key: "id",
    name: "ID",
    width: 80,
  },
  {
    key: "task",
    name: "Title",
    resizable: true,
    sortable: true,
    draggable: true,
  },
  {
    key: "priority",
    name: "Priority",
    resizable: true,
    sortable: true,
    draggable: true,
  },
  {
    key: "issueType",
    name: "Issue Type",
    resizable: true,
    sortable: true,
    draggable: true,
  },
  {
    key: "complete",
    name: "% Complete",
    resizable: true,
    sortable: true,
    draggable: true,
  },
];

export default function App() {
  const [rows] = useState(createRows);
  const [columnsOrder, setColumnsOrder] = useState((): readonly number[] =>
    columns.map((_, index) => index)
  );
  const [sortColumns, setSortColumns] = useState<readonly SortColumn[]>([]);
  const onSortColumnsChange = useCallback((sortColumns: SortColumn[]) => {
    setSortColumns(sortColumns.slice(-1));
  }, []);

  const reorderedColumns = useMemo(() => {
    return columnsOrder.map((index) => columns[index]);
  }, [columnsOrder]);

  const sortedRows = useMemo((): readonly Row[] => {
    if (sortColumns.length === 0) return rows;
    const { columnKey, direction } = sortColumns[0];

    let sortedRows: Row[] = [...rows];

    switch (columnKey) {
      case "task":
      case "priority":
      case "issueType":
        sortedRows = sortedRows.sort((a, b) =>
          a[columnKey].localeCompare(b[columnKey])
        );
        break;
      case "complete":
        sortedRows = sortedRows.sort((a, b) => a[columnKey] - b[columnKey]);
        break;
      default:
    }
    return direction === "DESC" ? sortedRows.reverse() : sortedRows;
  }, [rows, sortColumns]);

  function onColumnsReorder(sourceKey: string, targetKey: string) {
    setColumnsOrder((columnsOrder) => {
      const sourceColumnOrderIndex = columnsOrder.findIndex(
        (index) => columns[index].key === sourceKey
      );
      const targetColumnOrderIndex = columnsOrder.findIndex(
        (index) => columns[index].key === targetKey
      );
      const sourceColumnOrder = columnsOrder[sourceColumnOrderIndex];
      const newColumnsOrder = columnsOrder.toSpliced(sourceColumnOrderIndex, 1);
      newColumnsOrder.splice(targetColumnOrderIndex, 0, sourceColumnOrder);
      return newColumnsOrder;
    });
  }

  return (
    <DataGrid
      columns={reorderedColumns}
      rows={sortedRows}
      sortColumns={sortColumns}
      onSortColumnsChange={onSortColumnsChange}
      defaultColumnOptions={{ width: "1fr" }}
      onColumnsReorder={onColumnsReorder}
    />
  );
}

```

**Comment by balaji-kyro** [comment] 2024-08-29 09:33
<img width="1050" alt="Screenshot 2024-08-29 at 3 02 45 PM" src="https://github.com/user-attachments/assets/c67e4dd5-f004-4604-ac74-f3e78d416c3e">

It is working for me.

**Comment by softmarshmallow** [comment] 2024-08-29 12:16
Can you double check or perhaps share your screen recording? on my machine does not work for both on CSB and locally. - @see video

https://github.com/user-attachments/assets/7e7fb4de-5df1-4096-8f90-9430d90921ff

**Comment by Saurav017** [comment] 2024-08-30 03:15
Hello @softmarshmallow , if the issue is still open.  Can you please assign it to me.

**Comment by softmarshmallow** [comment] 2024-08-30 11:27
> Hello @softmarshmallow , if the issue is still open. Can you please assign it to me.

@Saurav017 Yes please. (I don't have permission to modify assignees on this issue)

**Comment by balaji-kyro** [comment] 2024-08-30 12:25
@softmarshmallow yes, It has happens sometimes.

**Comment by balaji-sivasakthi** [comment] 2024-08-30 13:06
@softmarshmallow 

The problem was caused by case sensitivity between event.dataTransfer.types and dragDropKey.

Ensure that the casing of dragDropKey matches exactly with the values used in event.dataTransfer.types. JavaScript string comparisons are case-sensitive, so a mismatch in casing can prevent the onDrop function from being triggered correctly.


<img width="590" alt="Screenshot 2024-08-30 at 6 09 56 PM" src="https://github.com/user-attachments/assets/a79e9ad6-87a0-4e33-9a97-5124b4af079a">

**Comment by balaji-sivasakthi** [comment] 2024-08-30 18:40
As per the drag event specification, the format argument value is converted to ASCII lowercase. When setting the `dragDropKey`, it is converted to lowercase, but when checking, we're doing so without converting it.

`useId()` returns a unique ID, but in some cases, it may return an uppercase value, which can cause issues. We should convert the key to lowercase to avoid this problem.

<img width="1310" alt="Screenshot 2024-08-30 at 11 34 54 PM" src="https://github.com/user-attachments/assets/ba4b821f-b8b3-4c8c-82f7-3a16d9f62485">


Ref https://html.spec.whatwg.org/multipage/dnd.html#the-datatransfer-interface

**Comment by Saurav017** [comment] 2024-08-31 02:09
hello @balaji-sivasakthi  , can I work on this issue ??

**Comment by balaji-kyro** [comment] 2024-08-31 06:09
> hello @balaji-sivasakthi  , can I work on this issue ??
> 

I already raised a PR for this issue.

**Comment by balaji-sivasakthi** [comment] 2024-08-31 06:13
> hello @balaji-sivasakthi  , can I work on this issue ??

I already raised a PR for this issue.

**Comment by amanmahajan7** [comment] 2024-09-06 18:30
Closing this as the fix has been merged

**Closed by amanmahajan7** 2024-09-06 18:30 UTC
Labels: Bug
