### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by damiandennis** [adazzle/react-data-grid#151] opened 2015-12-29 11:59 UTC
Hi just tried to download the latest version but get an error.
```
npm install react-data-grid
```

installing the specific version works.

```
npm install react-data-grid@v0.13.25
```

**Comment by malonecj** [comment] 2015-12-30 10:45
Hi this looks to be caused by an unofficial release being published. This should be fixed now

**Comment by mohak1990** [comment] 2016-01-01 15:59
I am able to download it on my 32bit PC. But not on my office PC which is 64bit. Which version should I download? Please help.

**Comment by mohak1990** [comment] 2016-01-02 15:19
Please solve my issue..

**Comment by vjdmathur** [comment] 2016-01-06 06:52
Same issue is with me. Cannot install. Tried specific version too.

**Comment by tseven** [comment] 2016-01-08 22:03
There appears to be an issue with the NPM package.

ls
Result of running 
```
$ npm install react-data-grid
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-data-grid"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/frank/.npm/react-data-grid/0.12.24/package.tgz archive: ENOENT: no such file or directory, open '/Users/frank/.npm/react-data-grid/0.12.24/package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /some/path/npm-debug.log
```
[npm-debug.log](http://pastebin.com/615tXP8c)

Specifying the version:
```
npm WARN ENOENT ENOENT: no such file or directory, open '/some/path/test_react/package.json'
npm WARN EPACKAGEJSON test_react No description
npm WARN EPACKAGEJSON test_react No repository field.
npm WARN EPACKAGEJSON test_react No README data
npm WARN EPACKAGEJSON test_react No license field.
```

Installing via bower appears broken since gulp and other possibly needed packages are ignored in the bower.json file:
```
 "ignore": [
    "gulp",
    "node_modules",
    "bower_components",
    "test",
    "tests",
    "src",
    "coveralls.yml",
    "gulpfile.js",
    "webpack.config.js",
    ".npmignore",
    ".gitignore",
    ".eslintrc",
    "examples",
    "config"
  ]
```
**This method worked for me:**
```
git clone git@github.com:adazzle/react-data-grid.git
cd react-data-grid
npm install envify@~1.2.0 && npm install
```

`envify` was missing. Installing it before-hand saves you a few steps.

**Comment by mohak1990** [comment] 2016-01-11 05:46
I am using webpack.. what should be the steps to fix this issue?

**Comment by jpdriver** [comment] 2016-01-26 19:16
closing this off as we've published a new version of `master` since it was opened. if you still have any issues please let us know.

**Closed by jpdriver** 2016-01-26 19:16 UTC

**Comment by mohak1990** [comment] 2016-01-27 05:30
![untitled](https://cloud.githubusercontent.com/assets/15984943/12604831/35e45626-c4e5-11e5-9bc7-015dbf32816c.png)
