### ISSUE TITLE
canary.10 and newer: Cell Range Selection not working anymore

### ISSUE THREAD

**Issue by gernotkogler** [adazzle/react-data-grid#1930] opened 2020-01-30 07:23 UTC
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit a support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behavior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

Since canary.10, I cannot select a range of cells by mouse or keyboard anymore. I noticed that canary.10 introduced an new API and I adopted it, but I cannot find an option to activate cell range selection, which obviously is now disabled by default.

What am I missing?

**Comment by maestroAlfredo** [comment] 2020-03-31 20:12
> * Have you already searched for similar issues? Please help us out and double-check first!
> * Also, please don't be that person who deletes this template. It's here for a reason.
> * Thanks!
> 
> ### Which version of React JS are you using?
> ✅ Officially supported ✅
> 
> * [ ]  v15.4.x
> 
> ⚠️ Not officially supported, expect warnings ⚠️
> 
> * [ ]  v15.5.x
> * [ ]  v15.6.x
> 
> ☣️ Not officially supported, expect warnings and errors ☣️
> 
> * [x]  v16.x.x
> 
> ### Which browser are you using?
> ✅ Officially supported ✅
> 
> * [ ]  IE 9 / IE 10 / IE 11
> * [ ]  Edge
> * [x]  Chrome
> 
> ⚠️ Not officially supported, but "should work" ⚠️
> 
> * [ ]  Firefox
> * [ ]  Safari
> 
> ### I'm submitting a ...
> * [x]  🐛 Bug Report
> * [ ]  💡 Feature Request
> 
> > 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> > Please do not submit a support request here. Instead see
> 
> > https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md
> 
> ### Issue Details
> ```
> Please include:
> - What the current behavior is
> - What the desired behavior is
> - (If Bug) Steps to reproduce the issue
> - (If Feature) The motivation / use case for the feature
> 
> We especially love screenshots / videos of problems, and remember
> The Best Issue Is A Pull Request™
> ```
> 
> Since canary.10, I cannot select a range of cells by mouse or keyboard anymore. I noticed that canary.10 introduced an new API and I adopted it, but I cannot find an option to activate cell range selection, which obviously is now disabled by default.
> 
> What am I missing?

Same issue here. I see the SelectionRangeMasks have been removed. Are there any plans to bring this back?

**Comment by farooq7124** [comment] 2020-05-10 08:59
Hi Team, 

Any plans to update on Cell range selection. I tried below config it is not working. it is very need feature as part of providing EXCEL sheet.

cellRangeSelection={{
          onStart: args => console.log(rows),
          onUpdate: args => console.log(rows),
          onComplete: args => console.log(rows)
        }}

Thanks team for great component

**Comment by AlexK1983** [comment] 2020-06-11 09:15
Hi Team, 
same wish to get this feature back , here :)

What happened to this method ?
Any reason you removed this functionality ?

**Comment by amanmahajan7** [comment] 2020-07-23 11:34
Cell range selection was quite buggy so we have removed it from canary for now but we have plans to add it back in the near future. However at this point this feature has not been prioritized. We are happy to accept a PR. Thank you all for you patience

**Comment by jmjuanico** [comment] 2020-09-23 05:05
i think there is this PR does this solve the bug? not sure what other bugs there is but this one is a blocker. https://github.com/adazzle/react-data-grid/issues/1416

**Comment by nstepien** [comment] 2021-08-17 17:35
Closing as duplicate of #2260

**Closed by nstepien** 2021-08-17 17:35 UTC

**Comment by babakansari** [comment] 2022-03-29 18:08
> Cell range selection was quite buggy so we have removed it from canary for now but we have plans to add it back in the near future. However at this point this feature has not been prioritized. We are happy to accept a PR. Thank you all for you patience

Is this PR go to be merged?
https://github.com/adazzle/react-data-grid/pull/2865
