### ISSUE TITLE
when a cloumn use "select" component, you need to click two or more time to pop up select options!

### ISSUE THREAD

**Issue by park365** [adazzle/react-data-grid#3225] opened 2023-05-11 09:11 UTC
## To Reproduce 

when a cloumn use "select" component, you need to click two or more time to pop up select options!

like demons: https://adazzle.github.io/react-data-grid/#/common-features, you will find first time you shuold click one more time to pop up select options

**Comment by godon019** [comment] 2023-05-13 12:53
I don't think this is a bug. it is just that the [demo's select component](https://github.com/adazzle/react-data-grid/blob/main/website/demos/components/Editors/dropDownEditor.tsx#L7) is implemented that way.

you can create your own Select component and have it open when the cell is focused
basically when the cell is clicked, it renders its child component
and the child component is what you can create by your own in a way that the component opens up when it is being rendered

something like this below
```tsx
export default function DropDownEditor() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    setOpen(true);
  }, []);

  return <Select open={open} />;
}

```

**Comment by farooq7124** [comment] 2023-05-13 13:21
@godon019   I have used react-select as dropdown component. But the problem is it will take width of column and because of that we can not set zindex to options container. Hence it results in having horizontal scroll bar.

Any suggestion how to avoid the scroll bar


https://github.com/adazzle/react-data-grid/assets/12643480/e2e5b7dd-13ab-4698-8050-745c8139f99b

**Comment by godon019** [comment] 2023-05-16 01:14
I am not familiar with react-select but I think there must be a way to pass style into react-select to make it bigger

**Comment by DVGY** [comment] 2023-07-03 15:09
@farooq7124 can you pls tell me how you achieved this ?

**Comment by amanmahajan7** [comment] 2024-11-25 02:51
Closing as the is not a bug in RDG

**Closed by amanmahajan7** 2024-11-25 02:51 UTC
Labels: Bug
