### ISSUE TITLE
Context Menus for multiple grids on same page conflict

### ISSUE THREAD

**Issue by ricemery** [adazzle/react-data-grid#814] opened 2017-06-01 17:31 UTC
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.4.2
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[x ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

Define two grids on the same page with unique ContextMenus. When clicking to display a context menu, both menus display layered on top of each other.

**Expected/desired behavior**

On a single grid, only the grid's ContextMenu should display. ContextMenus defined for other grids should not display.

**Reproduction of the problem**
I modified `example-18-context-menu.js` to replicate the problem. I added a second ReactDataGrid and unique ContextMenus.

```
  render() {
    return (
      <div>
      <ReactDataGrid
        contextMenu={<ContextMenu>
          <MenuItem >First context menu - first item</MenuItem>
          <MenuItem >First context menu - second item</MenuItem>
        </ContextMenu>}
        columns={this._columns}
        rowGetter={this.rowGetter}
        rowsCount={this.state.rows.length}
        minHeight={500} />
      <ReactDataGrid
        contextMenu={<ContextMenu>
          <MenuItem >Second context menu - first item</MenuItem>
        </ContextMenu>}
    columns={this._columns}
    rowGetter={this.rowGetter}
    rowsCount={this.state.rows.length}
    minHeight={500} />
      </div>
    );
  }
```

**What is the expected behavior?**

The example above will show multiple ReactDataGrids. When clicking on a grid to show a ContextMenu the "Second context menu" will overlay/partially hide the "First context menu". This happens regardless of which grid is right clicked.

**What is the motivation / use case for changing the behavior?**

Different ContextMenus/behavior for multiple grids.

**Comment by Michael-Tajmajer-Emrsn** [comment] 2017-08-17 19:36
Did you ever figure out a work around for this

**Comment by ricemery** [comment] 2017-08-17 19:51
@Michael-Tajmajer-Emrsn  - No, I never did find a work around. Sorry.

**Comment by Michael-Tajmajer-Emrsn** [comment] 2017-08-17 21:57
I dug into it and the problem is that the data grid used the same identifier for all the context menus.  I added an optional property to set the context menu id, which allows multiple menus to exist.

I'll see if I can figure out how to submit a PR with my changes.

**Comment by Michael-Tajmajer-Emrsn** [comment] 2017-08-17 22:07
No, I don't have access -- here's changes that will allow you to add a contextMenuId={"unique!"} to each of your menus.
[patch-for-context-menu.tar.gz](https://github.com/adazzle/react-data-grid/files/1232751/patch-for-context-menu.tar.gz)

**Comment by Keiyan** [comment] 2017-09-21 14:23
Thank you for the resolution, we have the same problem.
@committers : any chance the associated PR can make it to master quickly ?

**Comment by amanmahajan7** [comment] 2018-06-11 02:20
This has been fixed in https://github.com/adazzle/react-data-grid/pull/1081. `ContextMenuId` can be specified when a [context menu is created ](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-examples/src/scripts/example18-context-menu.js#L62)

**Closed by amanmahajan7** 2018-06-11 02:20 UTC
