### ISSUE TITLE
Warning: Cell: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

### ISSUE THREAD

**Issue by crazywako** [adazzle/react-data-grid#831] opened 2017-06-14 07:06 UTC
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[X] v15.6.0 https://facebook.github.io/react/blog/2017/06/13/react-v15.6.0.html
```
**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[X] Chrome
```
--------

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
```

**Current behavior**
Javascript error stating: ```warning.js:36 Warning: Cell: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.```

This has been anti-pattern a long time
[https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html)
```	  
// Cell.js


setScrollLeft: function setScrollLeft(scrollLeft) {
	    var ctrl = this; // flow on windows has an outdated react declaration, once that gets updated, we can remove this
	    if (ctrl.isMounted()) { 
	      var node = ReactDOM.findDOMNode(this);
	      if (node) {
	        var transform = 'translate3d(' + scrollLeft + 'px, 0px, 0px)';
	        node.style.webkitTransform = transform;
	        node.style.transform = transform;
	      }
	    }
	  },
```

**Expected/desired behavior**
No error.

**Comment by danawoodman** [comment] 2017-06-29 18:42
Same here! Hard to troubleshoot the cause...

**Comment by amanmahajan7** [comment] 2017-07-21 14:47
Fixed in https://github.com/adazzle/react-data-grid/pull/875

**Closed by amanmahajan7** 2017-07-21 14:47 UTC
