### ISSUE TITLE
Use in javascript 

### ISSUE THREAD

**Issue by ravi714** [adazzle/react-data-grid#3142] opened 2023-02-01 15:19 UTC
## Use case
How to use in custom rendering in javascript
Please give me a demo code
I need this urgently

**Comment by amanmahajan7** [comment] 2023-05-17 18:53
I am not sure what the issue is or if it is even related to RDG. I am closing this for now but feel free to create a new issue with clear details

**Closed by amanmahajan7** 2023-05-17 18:53 UTC
Labels: Feature Request
