### ISSUE TITLE
 webpack -w report error in windows

### ISSUE THREAD

**Issue by tonylinyy** [adazzle/react-data-grid#60] opened 2015-09-14 03:15 UTC
I use the  version: "0.13.0-alpha1" and webpack
it report the error:
```
ERROR in ./~/react-data-grid/dist/react-data-grid-with-addons.js
Module parse failed: \node_modules\react-data-grid\dist\react-data-grid-with-addons.js Line 4078: Duplicate data property in object literal not al
lowed in strict mode
You may need an appropriate loader to handle this file type.
|             return React.createElement('span', { className: 'glyphicon glyphicon-remove form-control-feedback' });
|           }
```
I check the code in dist/react-data-grid-with-addons.js
these two function duplicate:
render()
renderStatusIcon()
then I remove it, and webpack ok
something wrong?

**Comment by bakesteve** [comment] 2015-09-14 10:08
duplicate of #57

**Closed by bakesteve** 2015-09-14 10:08 UTC
