### ISSUE TITLE
Frozen Columns moving to middle of screen after refresh

### ISSUE THREAD

**Issue by LBWright** [adazzle/react-data-grid#1728] opened 2019-07-31 12:34 UTC
- Have you already searched for similar issues? Please help us out and double-check first!

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```
Current Behavior
When I freeze columns, and then scroll to the right, if there is an external state update that causes the grid to re-render, the grid updates and the frozen columns are in the middle of my screen.

Desired behavior:
When the Grid re-renders, the frozen columns should stay where they are.

You can see below, the checkboxes should be column 1, and the arrows should be column 2

![Screen Shot 2019-07-31 at 7 31 23 AM](https://user-images.githubusercontent.com/36030324/62212020-8969ec80-b365-11e9-9518-4c0cca49439d.png)

**Comment by LBWright** [comment] 2019-07-31 12:51
I don't mind forking and working on these issues, but it doesn't look like most of the contributor docs are up to date. 
You guys need help with some of these issues?
We're using this grid pretty intensively and we've found some pretty critical bugs with it inside our application. They're not a huge deal. We can work to fix them. Just give me a direction and I'll work to fix.

**Comment by LBWright** [comment] 2019-07-31 15:57
If anyone else is having this issue, you can manually fix the issue. We're using an effect to make sure that the grid itself and the dom element have matching properties.
```
// inside of our Grid Wrapper
  useEffect(() => {
    const canvas = grid.current.grid.querySelector('.react-grid-Canvas');
    if (!canvas) {
      return;
    }
    // the scrollLeft on the DOM and inside the the react ref were different
    if (canvas.scrollLeft !== grid.current.base._scrollLeft) {
      canvas.scrollTo(grid.current.base._scrollLeft, 0);
    }
  }, [filteredRows]);
```

**Comment by CoverNetIT** [comment] 2019-11-13 02:55
I found out the problem was caused by the scroll bar,and I could add some blank lines when there was no data

**Comment by amanmahajan7** [comment] 2020-04-30 01:53
This behavior should be fixed in v7 canary and we recommend upgrading 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Closed by amanmahajan7** 2020-04-30 01:53 UTC
