### ISSUE TITLE
index.js:8407 Warning: Row: `key` is not a prop. 

### ISSUE THREAD

**Issue by ZhengHe-MD** [adazzle/react-data-grid#321] opened 2016-05-17 03:17 UTC
I try the editable example in official site but get this warning. That doesn't influence the functions of data-grid. But I can't figure out the solution. I think there should be something like <ReactDataGrid.Row key={row.id} ... /> But don't know where to.

**Comment by udisun** [comment] 2016-05-22 14:55
+1

![image](https://cloud.githubusercontent.com/assets/950100/15454599/523e1412-2046-11e6-97ba-ef4a36bac183.png)

**Comment by tommiley** [comment] 2016-05-23 20:28
+1, I suspect the issue is React v15 which i forced upon react-data-grid unwillingly

**Comment by liuq** [comment] 2016-06-01 12:27
Yes, it's definitely a react v15 issue +1

**Comment by jetpackjarrett** [comment] 2016-06-14 18:18
+1

**Comment by wnoveno** [comment] 2016-06-15 10:01
So, does this mean that React v15 is not supported at the moment? I can create a PR for this if needed

**Comment by malonecj** [comment] 2016-06-16 12:39
We will welcome PR for React 15, thanks

**Comment by diogofcunha** [comment] 2016-08-24 12:19
This was addressed in #370

**Closed by diogofcunha** 2016-08-24 12:19 UTC
