### ISSUE TITLE
Grid is not correctly rendered after window resize

### ISSUE THREAD

**Issue by martinnov92** [adazzle/react-data-grid#916] opened 2017-09-01 10:50 UTC
### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

Hello does anyone has same issues as we do?

![image](https://user-images.githubusercontent.com/15011249/29966721-7c5451b6-8f13-11e7-8ec8-21ed8747d18d.png)

Sometimes when I resize window or pane in splitter the grid does not get correctly rendered, there are columns and rows missing...

Thank you

**Comment by martinnov92** [comment] 2017-09-01 12:25
For now I solved it by calling resize events twice with setTimeout(resize, 0), but I don´t think this is very good solution...

**Comment by zguillen** [comment] 2017-09-27 19:48
Hi - We are having exact same problem.  Can you give more details on how you worked around this bug with resize events?

**Comment by csbhut** [comment] 2017-10-17 09:28
@martinnov92 even we are facing same problem . It will be very helpfull if you can share about workaround...

**Comment by martinnov92** [comment] 2017-10-17 10:21
Hello, as I wrote before, all I did was to call window resize event twice, something like this: 
```
        const resizeEvent = document.createEvent("HTMLEvents");
        resizeEvent.initEvent('resize', true, false);
        window.dispatchEvent(resizeEvent);
        setTimeout(() => {  window.dispatchEvent(resizeEvent) }, 0);
```

**Comment by zguillen** [comment] 2017-10-26 21:30
Hey guys, I was still seeing the bug after dispatching a duplicate window resize event as @martinnov92 mentioned.  But what I did get to work was this:
`import { WindowResizeListener } from 'react-window-resize-listener';`
`    constructor(props) {`
`        super(props);`
``
`        this.justLoaded = true;`
`        this.windowResized = false;`
`    }`
`...`
`render() {`
`if (this.windowResized) {`
`                this.forceRedraw();`
`                return <div/>;`
`            } else {`
`                <WindowResizeListener onResize={this.handleWindowResize}/>`
`                <ReactDataGrid ...>`
`            }`
`...`
`}`
``
`handleWindowResize = (windowSize) => {`
`        //the table itself fires a windowResize event for some reason immediately after`
`        //its done rendering, so ignore that one as its not a true resize event.`
`        if (!this.justLoaded) {`
`            this.windowResized = true;`
`            this.forceUpdate();`
`        } else {`
`            this.justLoaded = false;`
`        }`
`    }`
`    forceRedraw = () => {`
`        this.justLoaded = true;`
`        this.windowResized = false;`
`        this.forceUpdate();`
`    }`

**Comment by rlreamy** [comment] 2018-01-22 20:10
We are also having the same issue.  We have a hide-able div, and when it is hidden, the container for the table is enlarged, but react-data-grid is not resizing.

**Comment by jacek-jaskolski** [comment] 2018-03-13 13:00
@martinnov92 Thank you very much. That was exactly what I was looking for!

**Comment by rlreamy** [comment] 2018-07-12 17:51
I do not believe this issue has been resolved.

**Comment by Digi-Hessam** [comment] 2018-07-24 07:29
+1

Also seeing this issue.

**Comment by Gajesh-LH** [comment] 2018-08-03 09:53
+1 

I am facing the type of similar issue. I am finding a workaround but not getting proper solution. Can anyone have solved this issue?

[Click here to see the recorded screen](http://recordit.co/aLR82jVyDA)

<img width="1280" alt="screen shot 2018-08-03 at 3 10 13 pm" src="https://user-images.githubusercontent.com/38095258/43636942-25ae6136-9731-11e8-8a65-74e2739a011b.png">
<img width="1280" alt="screen shot 2018-08-03 at 3 10 23 pm" src="https://user-images.githubusercontent.com/38095258/43636943-25d796fa-9731-11e8-82df-c34abaf8d979.png">

**Comment by WDRed** [comment] 2018-08-23 13:04
@Digi-Hessam your solution adds another bug - on vertical scroll all columns content disappears. 
Fix is to add this.grid.onColumnResize(n1, n2) to componentDidMount(). But you need to add a little hook to make all columns size not 80px (min size for column).

**Comment by Digi-Hessam** [comment] 2018-08-23 14:31
@WDRed - Well, I'm not experiencing that issue. Maybe because all my rows are rendered at load (not what I intended, and havn't done anything to force it to render all rows).

**Comment by shridharbennisur** [comment] 2018-09-11 10:48
@martinnov92 - I am also using splitter component still facing  issue, can you please provide some more details.

**Comment by martinnov92** [comment] 2018-09-11 10:52
Hello @shridharbennisur , try to follow my previous comment https://github.com/adazzle/react-data-grid/issues/916#issuecomment-337187269. All I did was to provide callback function whenever I release the splitter (onDragEnd/onMouseUp,...). Hope it helps

**Comment by shridharbennisur** [comment] 2018-09-11 11:56
HI @martinnov92 , Is their any way to call resize event on rowclick.

**Comment by rlreamy** [comment] 2018-10-11 14:57
This is still an issue, and we would really appreciate it being resolved.  It looks like there is an outstanding pull request, is there any way this could get reviewed and merged?

**Comment by galleyrob** [comment] 2018-10-17 14:32
This is still a major issue across all browsers, can it be resolved, dont want to start adding resize listeners if its resolvable

**Comment by galleyrob** [comment] 2018-10-19 05:45
above fixes are very sketchy and dont really work, this is a major headache with this grid can this be looked at urgently please

**Closed** 2018-11-29 07:20 UTC
Labels: wontfix

**Comment by shortwavedave** [comment] 2019-09-19 09:37
I can confirm the same problem

**Comment by shortwavedave** [comment] 2019-09-21 11:47
Here is a gif of the situation:

![reactdatagrid](https://user-images.githubusercontent.com/22798574/65372869-ecea0980-dc86-11e9-8aea-d3056a13a563.gif)

I have to resize the window to make it fit correctly, so it doesn't render right in full screen. This is the code:

```
 <Panel style={{color: "rgb(255,255,255)"}} defaultExpanded>
                <Panel.Heading>
                    <Panel.Title toggle>
                        Fleet
                    </Panel.Title>
                </Panel.Heading>
                <Panel.Body collapsible>
                    <ReactDataGrid
                        columns={columns}
                        rowGetter={i => rows[i]}
                        rowsCount={rows.length}
                    />
                </Panel.Body>
            </Panel>
```
