### ISSUE TITLE
Select a range of cells programatically like on load in React Data Grid

### ISSUE THREAD

**Issue by Tarun-1994-Kumar** [adazzle/react-data-grid#1922] opened 2020-01-24 12:00 UTC
Hi everyone,
            I have a requirement where in I need to select range of data from react table like for example cell (1,1) to cell(6,6) onload without dragging and selecting on the table.Is there a way we can do this in React Data Grid?

**Comment by zofbanach** [comment] 2021-01-08 10:21
@Tarun-1994-Kumar Hi, I have similar requirement. Have you found any solution or workaround?

**Comment by nstepien** [comment] 2021-08-17 17:35
Closing as duplicate of #2260

**Closed by nstepien** 2021-08-17 17:35 UTC
