### ISSUE TITLE
onToggleFilter option not working

### ISSUE THREAD

**Issue by topgun743** [adazzle/react-data-grid#1034] opened 2017-11-23 13:49 UTC
### react-data-grid-addons 2.0.49

I am using Toolbar component with react-data-grid. Here is the code:

```
<ReactDataGrid
            columns={this.state.columns}
            rowGetter={(i) => this.rowGetter(i)}
            rowsCount={this.state.rows.length}
            minHeight={300}
            toolbar={<Toolbar 
                enableFilter={true}
                filterRowsButtonText="Filter"
                onToggleFilter={this.onToggleFilterButton}
            />}
            onAddFilter={this.handleFilterChange}
            onClearFilters={() => this.onClearFilters()}
        />
```

```onToggleFilterButton()``` function is not firing. Although filters do show/hide whenever I click on Filter button.

Can someone please tell what am I missing?

**Comment by milesrichardson** [comment] 2017-11-23 14:30
Funny, I'm having this problem at the exact same time as you.

Still working out the best solution, but the problem is that the `Grid` component injects its own `onToggleFilter` prop into the `Toolbar` component that you define, effectively overriding your prop.

**Comment by topgun743** [comment] 2017-11-23 14:31
I am banging my head over it for the last 4 hours. Still no clue.

**Comment by milesrichardson** [comment] 2017-11-23 14:51
Here's how I solved it with [higher order components](https://reactjs.org/docs/higher-order-components.html):

``` js
const toolbarWrapper = (ToolbarComponent, onToggleFilter) => {

    return class extends Component {
        render() {

            const origOnToggleFilter = this.props.onToggleFilter
            const newOnToggleFilter = () => {
                origOnToggleFilter()
                onToggleFilter()
            }

            return <ToolbarComponent {...this.props} onToggleFilter={newOnToggleFilter} />
        }
    }
}

const MyToolbar = toolbarWrapper(Toolbar, (e) => console.log('Custom filter toggle function'))
```
Then use `MyToolbar` just as you would `Toolbar`:

``` js
<ReactDataGrid
                   //...
                    toolbar={
                        <MyToolbar enableFilter={true} onToggleFilter={this.handleToggleFilter.bind(this)}>
                            <div>A child</div>
                        </MyToolbar>
                    }
                    //....
                    />
```

**Comment by milesrichardson** [comment] 2018-07-12 13:56
AFAIK this is still a bug...

Closing bugs because you haven't fixed them quickly enough !== closing bugs because they aren't bugs

**Closed** 2018-08-18 15:37 UTC
Labels: bug, wontfix
